### PR TITLE
remove __qPCR_ suffix from sample name because it is super annoying

### PR DESCRIPTION
**Pull request by vezzi**

### CODE REVIEW

**Comment by Galithil** [comment]
No check about the existence of the field "SampleName" ?

**Comment by vezzi** [comment]
@Galithil added check about presence of SampleName in SampleSheet

**Comment by Galithil** [comment]
I really, really don't like this. An automated rewrite of a field as a default behaviour, without any argument, is the prime example of something that can be a pain in the neck of whoever decides to use this package at some point (thinking about clinical, or even uppsala.)
I guess I'll have to rewrite it.

**Comment by vezzi** [comment]
@Galithil I can add an option --remove-qPCR-suffix it will take no time. I do not think that this will improve so much the clarity of this check anyway. I will do it.

**Comment by vezzi** [comment]
@Galithil ok now the _qPCR removal is a stand alone function. it needs to be called from TACA.

**Comment by vezzi** [comment]
@Galithil have a look to this

**Pull request merged**
